version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders      
    ports:
      - "3306:3306" 
    networks:
      - go-clean-arch 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672"     
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - go-clean-arch

  app:
    build: .
    depends_on:
      - rabbitmq
      - mysql
    #entrypoint: ["/app/wait-for-it.sh", "rabbitmq:5672", "--timeout=20", "--", "/app/orders"]    
    entrypoint: ["/bin/sh", "-c", "/app/wait-for-it.sh rabbitmq:5672 --timeout=20 && /app/wait-for-it.sh mysql:3306 --timeout=20 && make migrate && /app/orders"] 
    ports:
      - "8080:8080"
      - "8000:8000"
      - "50051:50051"
    networks:
      - go-clean-arch

networks:
  go-clean-arch:
    driver: bridge
