POST http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "id":"aa01",
    "price": 210.6,
    "tax": 1.8
}

###

GET http://localhost:8000/order
Content-Type: application/json
