POST http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "id":"aa03",
    "price": 150.6,
    "tax": 1.5
}

###

GET http://localhost:8000/order
Content-Type: application/json
